name: PR 코드 분석

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: settings java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod gradle
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew --info test

      - name: Run an analysis of the ${{ github.REF }} branch ${{ github.BASE_REF }} base
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          args: >
            -Dsonar.issuesReport.console.enable=true 
            -Dsonar.projectKey=sonarqube-test
            -Dsonar.java.libraries= 
            -Dsonar.java.libraries.empty=true 
            -Dsonar.java.binaries=build/classes
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.test.inclusions=**/*Test.java 
            -Dsonar.exclusions=**/*Application** 
            -Dsonar.sourceEncoding=UTF-8 
            -Dsonar.java.coveragePlugin=jacoco 
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport.xml

      - name: SonarQube Quality Check
        id: sonar-quality
        run: |
          SONAR_PROJECT_KEY="sonarqube-test" 
          SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"

          RESULT=$(curl -s -u "admin:root" "${{ secrets.SONAR_URL }}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}&pullRequest=${{github.event.number}}")
          STATUS=$(echo "$RESULT" | jq -r '.projectStatus.status')
          ERROR_METRIC_KEYS=$(echo "$RESULT" | jq -r '.projectStatus.conditions[] | select(.status == "ERROR").metricKey')
          
          echo "STATUS=${STATUS}" >> $GITHUB_OUTPUT
          echo "ERROR_METRIC_KEYS=${ERROR_METRIC_KEYS}" >> $GITHUB_OUTPUT

      - name: variable test
        run: |
          echo "${{ github.event.pull_request.user.login }}"

      - name: slack test
        run: |
          SLACK_DATA='{ "text": "PR 브랜치 분석", "blocks": [ { "type": "section", "text": {"type":"mrkdwn","text": "'
          <${{ secrets.${ github.event.pull_request.user.login } }}>"  }}]}'
          if [ "${{ github.event.pull_request.user.login }}" == "apptie" ]; then
            SLACK_DATA=SLACK_DATA+${{ secrets.apptie }}
          SLACK_DATA=SLACK_DATA+'" }}]}'
          
          curl -X POST ${{ secrets.SLACK_WEBHOOK }} \
          -d "${SLACK_DATA}"
