name: PR 코드 분석

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: settings java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod gradle
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew --info test

      - name: Run an analysis of the ${{ github.REF }} branch ${{ github.BASE_REF }} base
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          args: >
            -Dsonar.issuesReport.console.enable=true 
            -Dsonar.projectKey=sonarqube-test
            -Dsonar.java.libraries= 
            -Dsonar.java.libraries.empty=true 
            -Dsonar.java.binaries=build/classes
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.test.inclusions=**/*Test.java 
            -Dsonar.exclusions=**/*Application** 
            -Dsonar.sourceEncoding=UTF-8 
            -Dsonar.java.coveragePlugin=jacoco 
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport.xml

      - name: SonarQube Quality Check
        id: sonar-quality
        run: |
          SONAR_PROJECT_KEY="sonarqube-test" 
          SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"

          RESULT=$(curl -s -u "admin:root" "${{ secrets.SONAR_URL }}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}&pullRequest=${{github.event.number}}")
          STATUS=$(echo "$RESULT" | jq -r '.projectStatus.status')
          ERROR_METRIC_KEYS=$(echo "$RESULT" | jq -r '.projectStatus.conditions[] | select(.status == "ERROR").metricKey')
          
          echo "STATUS=${STATUS}" >> $GITHUB_OUTPUT
          echo "ERROR_METRIC_KEYS=${ERROR_METRIC_KEYS}" >> $GITHUB_OUTPUT

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        if: ${{ steps.sonar-quality.outputs.STATUS == 'OK' }}
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: 'green'
          SLACK_TITLE: '메세지'
          SLACK_MESSAGE: 'pull request 요청 성공'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        if: ${{ steps.sonar-quality.outputs.STATUS != 'OK' }}
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: 'red'
          SLACK_TITLE: '메세지'
          SLACK_MESSAGE: 'pull request 요청 실패 - ${{ steps.sonar-quality.outputs.ERROR_METRIC_KEYS }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
